learning_user/basic_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('registration',views.registration,name='registration'),
    path('user_login',views.user_login,name='user_login'),
]

learning_user/learning_user/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

learning_user/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.DO_NOTHING)

    # additional classes
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)


    def __str__(self):
        return self.user.username

learning_user/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db.models import fields
from django.forms.models import model_to_dict
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_user/basic_app/views.py
import basic_app
from django.contrib.auth.models import User
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse 
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

def registration(request):

    registered = False
    if request.method == "POST":
        user_form = UserForm (data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
    
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            # user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()


    return render(request,'basic_app/registration.html',
                                {'user_form':user_form,
                                    'profile_form':profile_form,
                                    'registered':registered})
                                

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')


        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return render(request,'basic_app/index.html')


            else:
                return HttpResponse("Account Not Active")

        else:
            print("Someone failed to login")
            print(f"Username: {username} and Password: {password}")
            return HttpResponse("INVALID LOGIN DEATILS")

    else:
        return render(request,'basic_app/login.html',{})

@login_required
def special(request):
    return HttpResponse("You are logged in")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic_app:index'))
    

learning_user/templates/basic_app/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <nav class='navbar navbar-default navbar-static-top'>
            <div class='container'>
                <ul class="nav navbar-nav">
                    <li><a class='navbar-brand' href='{% url 'basic_app:index' %}'>Index</a></li>
                    <li><a class='navbar-brand' href='{% url 'basic_app:registration' %}'>Registration</a></li>

                    {% if user.is_authenticated %}

                        <li><a class='navbar-brand' href='{% url 'logout' %}'>Logout</a></li>
                    {% else %}
                        <li><a class='navbar-brand' href='{% url 'basic_app:user_login' %}'>Login</a></li>
                        
                    {% endif %}


                </ul>

            </div>
        </nav>

        {% block body_block %}
        {% endblock body_block %}
        <script src="" async defer></script>
    </body>
</html>

learning_user/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
        <h1>Index</h1>
</div>
{% endblock body_block %}
   

learning_user/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class='container'>
    <h1>Please login</h1>

    <form action='{% url 'basic_app:user_login' %}' method='post'>
        {% csrf_token %}
        <label for='username'>Username</label>
        <input type='text' name='username' placeholder='Enter Username'>
        
        <label for='password'>Password</label>
        <input type='password' name='password' placeholder='Enter Password'>

        <input type='submit' class='btn btn-primary' value='Login'>

    </form>
</div`>

{% endblock body_block %}

learning_user/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="container">
        
        <h1><a href='{% url 'basic_app:user_login' %}'>Login Here</a></h1>
        {% if registered %}
            <h1>Thank you :)</h1>
        
        {% else %}
            <h1>Register here!</h1>
            <h3>Fill out the form</h3>

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{user_form.as_p}}
                {{profile_form.as_p}}
                <input type='submit' name='' value="Register">
            </form>
        {% endif %}
</div>
{% endblock body_block %}
   